-- GENERATED by fixtures/matrix/gen.py -- do not edit by hand.
--
-- One relation per RLS configuration, named for its own state, so an
-- eval mismatch names the state rather than an arbitrary table.

-- rls=True select=none insert=none notnull=True
CREATE TABLE m_rls_selnone_insnone_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selnone_insnone_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selnone_insnone_nn ENABLE ROW LEVEL SECURITY;

-- rls=True select=none insert=none notnull=False
CREATE TABLE m_rls_selnone_insnone_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selnone_insnone_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selnone_insnone_nul ENABLE ROW LEVEL SECURITY;

-- rls=True select=none insert=anon notnull=True
CREATE TABLE m_rls_selnone_insanon_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selnone_insanon_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selnone_insanon_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selnone_insanon_nn_ins" ON m_rls_selnone_insanon_nn FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=none insert=anon notnull=False
CREATE TABLE m_rls_selnone_insanon_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selnone_insanon_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selnone_insanon_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selnone_insanon_nul_ins" ON m_rls_selnone_insanon_nul FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=anon insert=none notnull=True
CREATE TABLE m_rls_selanon_insnone_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selanon_insnone_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selanon_insnone_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selanon_insnone_nn_sel" ON m_rls_selanon_insnone_nn FOR SELECT TO anon USING (true);

-- rls=True select=anon insert=none notnull=False
CREATE TABLE m_rls_selanon_insnone_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selanon_insnone_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selanon_insnone_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selanon_insnone_nul_sel" ON m_rls_selanon_insnone_nul FOR SELECT TO anon USING (true);

-- rls=True select=anon insert=anon notnull=True
CREATE TABLE m_rls_selanon_insanon_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selanon_insanon_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selanon_insanon_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selanon_insanon_nn_sel" ON m_rls_selanon_insanon_nn FOR SELECT TO anon USING (true);
CREATE POLICY "m_rls_selanon_insanon_nn_ins" ON m_rls_selanon_insanon_nn FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=anon insert=anon notnull=False
CREATE TABLE m_rls_selanon_insanon_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selanon_insanon_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selanon_insanon_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selanon_insanon_nul_sel" ON m_rls_selanon_insanon_nul FOR SELECT TO anon USING (true);
CREATE POLICY "m_rls_selanon_insanon_nul_ins" ON m_rls_selanon_insanon_nul FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=authenticated insert=none notnull=True
CREATE TABLE m_rls_selauthenticated_insnone_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selauthenticated_insnone_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selauthenticated_insnone_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selauthenticated_insnone_nn_sel" ON m_rls_selauthenticated_insnone_nn FOR SELECT TO authenticated USING (true);

-- rls=True select=authenticated insert=none notnull=False
CREATE TABLE m_rls_selauthenticated_insnone_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selauthenticated_insnone_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selauthenticated_insnone_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selauthenticated_insnone_nul_sel" ON m_rls_selauthenticated_insnone_nul FOR SELECT TO authenticated USING (true);

-- rls=True select=authenticated insert=anon notnull=True
CREATE TABLE m_rls_selauthenticated_insanon_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selauthenticated_insanon_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selauthenticated_insanon_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selauthenticated_insanon_nn_sel" ON m_rls_selauthenticated_insanon_nn FOR SELECT TO authenticated USING (true);
CREATE POLICY "m_rls_selauthenticated_insanon_nn_ins" ON m_rls_selauthenticated_insanon_nn FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=authenticated insert=anon notnull=False
CREATE TABLE m_rls_selauthenticated_insanon_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selauthenticated_insanon_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selauthenticated_insanon_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selauthenticated_insanon_nul_sel" ON m_rls_selauthenticated_insanon_nul FOR SELECT TO authenticated USING (true);
CREATE POLICY "m_rls_selauthenticated_insanon_nul_ins" ON m_rls_selauthenticated_insanon_nul FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=owner insert=none notnull=True
CREATE TABLE m_rls_selowner_insnone_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selowner_insnone_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selowner_insnone_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selowner_insnone_nn_sel" ON m_rls_selowner_insnone_nn FOR SELECT TO authenticated USING (owner_id::text = current_setting('request.jwt.claims', true)::json->>'sub');

-- rls=True select=owner insert=none notnull=False
CREATE TABLE m_rls_selowner_insnone_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selowner_insnone_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selowner_insnone_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selowner_insnone_nul_sel" ON m_rls_selowner_insnone_nul FOR SELECT TO authenticated USING (owner_id::text = current_setting('request.jwt.claims', true)::json->>'sub');

-- rls=True select=owner insert=anon notnull=True
CREATE TABLE m_rls_selowner_insanon_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_rls_selowner_insanon_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selowner_insanon_nn ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selowner_insanon_nn_sel" ON m_rls_selowner_insanon_nn FOR SELECT TO authenticated USING (owner_id::text = current_setting('request.jwt.claims', true)::json->>'sub');
CREATE POLICY "m_rls_selowner_insanon_nn_ins" ON m_rls_selowner_insanon_nn FOR INSERT TO anon WITH CHECK (true);

-- rls=True select=owner insert=anon notnull=False
CREATE TABLE m_rls_selowner_insanon_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_rls_selowner_insanon_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;
ALTER TABLE m_rls_selowner_insanon_nul ENABLE ROW LEVEL SECURITY;
CREATE POLICY "m_rls_selowner_insanon_nul_sel" ON m_rls_selowner_insanon_nul FOR SELECT TO authenticated USING (owner_id::text = current_setting('request.jwt.claims', true)::json->>'sub');
CREATE POLICY "m_rls_selowner_insanon_nul_ins" ON m_rls_selowner_insanon_nul FOR INSERT TO anon WITH CHECK (true);

-- rls=False select=none insert=none notnull=True
CREATE TABLE m_norls_selnone_insnone_nn (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text NOT NULL
);
INSERT INTO m_norls_selnone_insnone_nn (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;

-- rls=False select=none insert=none notnull=False
CREATE TABLE m_norls_selnone_insnone_nul (
  id       bigserial PRIMARY KEY,
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload text
);
INSERT INTO m_norls_selnone_insnone_nul (payload) SELECT 'row-' || g FROM generate_series(1, 6) g;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
