#!/usr/bin/env python3
"""Generate a schema covering the full RLS state space, plus its answer key.

The three existing eval targets cover states somebody thought of. That is a
real limit: a hand-picked fixture cannot surface a classifier bug in a
combination nobody considered, and "it passes on three targets" is a weak claim
about a tool whose whole selling point is not missing things.

This generates the cross product instead:

    RLS enabled/disabled
  x SELECT policy: none | anon | authenticated | owner-scoped
  x INSERT policy: none | anon
  x every column nullable / a NOT NULL column present

Each combination becomes one relation named for its own configuration, so a
mismatch in eval output identifies the state directly rather than a table name.

The answer key is DERIVED FROM THE SAME RULES that emit the DDL, in one pass,
so the two cannot drift and there is no hand transcription to get wrong. The
expectations are Postgres semantics, not observations:

    readable  = RLS off, or a SELECT policy admits the anon role
    writable  = RLS off, or an INSERT policy admits the anon role

Note what the second rule does NOT say. A policy written TO authenticated does
not make the relation anon-readable, and an owner-scoped policy admits nobody
whose JWT subject fails the predicate — including every anonymous caller. Both
are cases a naive scanner conflates with "has a policy, therefore open".

Regenerate with:  python3 fixtures/matrix/gen.py
"""
from __future__ import annotations
import itertools
import pathlib

HERE = pathlib.Path(__file__).parent
REPO = HERE.parent.parent

RLS = [True, False]
SELECT_POLICY = ["none", "anon", "authenticated", "owner"]
INSERT_POLICY = ["none", "anon"]
NOTNULL = [True, False]

SEED_ROWS = 6


def name(rls: bool, sel: str, ins: str, notnull: bool) -> str:
    return "m_{}_{}_{}_{}".format(
        "rls" if rls else "norls", f"sel{sel}", f"ins{ins}",
        "nn" if notnull else "nul")


def readable(rls: bool, sel: str) -> bool:
    """Anon sees rows when RLS is off, or a policy explicitly admits anon."""
    if not rls:
        return True
    return sel == "anon"


def writable(rls: bool, ins: str) -> bool:
    """Anon may INSERT when RLS is off, or an INSERT policy admits anon."""
    if not rls:
        return True
    return ins == "anon"


def ddl(rls: bool, sel: str, ins: str, notnull: bool) -> str:
    t = name(rls, sel, ins, notnull)
    payload = "payload text NOT NULL" if notnull else "payload text"
    out = [
        f"CREATE TABLE {t} (",
        "  id       bigserial PRIMARY KEY,",
        "  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),",
        f"  {payload}",
        ");",
        f"INSERT INTO {t} (payload) SELECT 'row-' || g "
        f"FROM generate_series(1, {SEED_ROWS}) g;",
    ]
    if rls:
        out.append(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
        if sel == "anon":
            out.append(f'CREATE POLICY "{t}_sel" ON {t} FOR SELECT TO anon USING (true);')
        elif sel == "authenticated":
            out.append(f'CREATE POLICY "{t}_sel" ON {t} '
                       f"FOR SELECT TO authenticated USING (true);")
        elif sel == "owner":
            out.append(
                f'CREATE POLICY "{t}_sel" ON {t} FOR SELECT TO authenticated '
                "USING (owner_id::text = "
                "current_setting('request.jwt.claims', true)::json->>'sub');")
        if ins == "anon":
            out.append(f'CREATE POLICY "{t}_ins" ON {t} '
                       f"FOR INSERT TO anon WITH CHECK (true);")
    return "\n".join(out)


def main() -> None:
    combos = list(itertools.product(RLS, SELECT_POLICY, INSERT_POLICY, NOTNULL))
    # RLS off makes the policy columns meaningless, so keep one representative
    # per (notnull) rather than eight identical relations.
    seen_norls: set[bool] = set()
    kept = []
    for rls, sel, ins, nn in combos:
        if not rls:
            if nn in seen_norls:
                continue
            seen_norls.add(nn)
            sel, ins = "none", "none"
        kept.append((rls, sel, ins, nn))

    sql = [
        "-- GENERATED by fixtures/matrix/gen.py -- do not edit by hand.",
        "--",
        "-- One relation per RLS configuration, named for its own state, so an",
        "-- eval mismatch names the state rather than an arbitrary table.",
        "",
    ]
    relations = []
    for rls, sel, ins, nn in kept:
        t = name(rls, sel, ins, nn)
        sql.append(f"-- rls={rls} select={sel} insert={ins} notnull={nn}")
        sql.append(ddl(rls, sel, ins, nn))
        sql.append("")
        relations.append({
            "name": t,
            "rows": SEED_ROWS if readable(rls, sel) else 0,
            "read_exposed": readable(rls, sel),
            "insert_reachable": writable(rls, ins),
        })

    sql += [
        "GRANT USAGE ON SCHEMA public TO anon, authenticated;",
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public "
        "TO anon, authenticated;",
        "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;",
        "",
    ]
    (HERE / "schema" / "01_matrix.sql").write_text("\n".join(sql))

    rel_yaml = []
    for r in sorted(relations, key=lambda x: x["name"]):
        rel_yaml += [
            f"    - name: {r['name']}",
            f"      rows: {r['rows']}",
            f"      read_exposed: {str(r['read_exposed']).lower()}",
            f"      insert_reachable: {str(r['insert_reachable']).lower()}",
        ]

    readable_n = sum(1 for r in relations if r["read_exposed"])
    writable_n = sum(1 for r in relations if r["insert_reachable"])

    target = f"""# GENERATED by fixtures/matrix/gen.py -- do not edit by hand.
#
# The full RLS state space, and its answer key derived from the same rules that
# emit the DDL. Hand-written fixtures cover states somebody thought of; this
# covers the cross product, including the combinations that trip a classifier
# reasoning by shortcut:
#
#   - a SELECT policy TO authenticated does NOT make a relation anon-readable
#   - an owner-scoped policy admits nobody whose JWT subject fails the
#     predicate, which includes every anonymous caller
#   - a relation can accept anonymous INSERT while refusing every anonymous
#     SELECT, and vice versa
#
#   cd fixtures/matrix && docker compose up -d
#   export UNRULY_MATRIX_KEY=$(cat anon.jwt)

name: matrix-fixture
project_ref: matrix
base_url: http://127.0.0.1:54341
rest_prefix: /
anon_key_env: UNRULY_MATRIX_KEY
fixture: true

notes: >
  {len(relations)} relations spanning every combination of RLS on/off, four
  SELECT policy shapes, two INSERT policy shapes, and nullable vs NOT NULL
  columns. {readable_n} are anon-readable and {writable_n} accept anonymous
  INSERT by construction.

expect:
  key_in_bundles: false
  routines: []

  relations:
{chr(10).join(rel_yaml)}
"""
    (REPO / "evals" / "targets" / "matrix-fixture.yaml").write_text(target)

    print(f"{len(relations)} relations: {readable_n} readable, {writable_n} writable")


if __name__ == "__main__":
    main()
